### ISSUE TITLE
BBUart library in attiny13

### ISSUE THREAD

**Issue by BorisSpa** [nerdralph/nerdralph#3]
Hi. I'm using your library to extract some values from an Attiny13a mounted on a radio.

Since I have limited access to the hardware, I want to send some bytes from the attiny port PB5 (physical pin 1) and read them in an arduino board that later on will play with those values and do other stuff.

To do so, using an arduino ISP, I load this code into the Attiny13:

```
#include <avr/io.h>
#include <BBUart.h>

void setup(){
}

void serOut(const char* str)
{
   while (*str) TxByte (*str++);
}

void loop(){
  serOut("Hello");
  delay(1000);
}
```

And I modified the BBUart.S so the pin looks like this:

```
#define UART_Tx 5
#define UART_Rx 5
```

Also I had to rename the `dummy` functions to `dummy_foo` as arduino IDE was complaining about some redefinition of a function

-------

After that code is loaded into the attiny13 I only leave the PB5 pin of the attiny13 connected to pin 0 of the arduino (along with +5 and GND)

On the arduino this is the code I upload to read values. It just lights up the led after it recieves something but it never works as I don't recieve anything:

```
void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
  Serial.begin(115200);
}

void loop() {
  if (Serial.available()) {
    digitalWrite(LED_BUILTIN, HIGH);
    char receivedByte = Serial.read();
  }
}
```
I also tried using the` SoftwareSerial` library on pin0 at 115200 baud but without success :(

Do you know how I can read those values or do you have any working example that reads the attiny values from an arduino?
Thanks a lot for your help and for the library

**Comment by BorisSpa** [comment]
Closing since pin5 cannot be used as IO unless fuses are modified

**Comment by nerdralph** [comment]
I'd recommend you try PicoUART.
http://nerdralph.blogspot.com/2020/02/building-better-bit-bang-uart-picouart.html
